http:
  serversTransports:
    scrypted-insecure:
      insecureSkipVerify: true

  routers:
    scrypted:
      rule: "Host(`scrypted.{{ env `NEXUS_DOMAIN` }}`)"
      entryPoints:
        - "https"
      middlewares:
        - "tailscale-chain@file"
      service: "scrypted"
      tls:
        certResolver: "certchallenge"

    scrypted-http:
      rule: "Host(`scrypted.{{ env `NEXUS_DOMAIN` }}`)"
      entryPoints:
        - "http"
      middlewares:
        - "redirect-to-https@file"
      service: "scrypted"

  services:
    scrypted:
      loadBalancer:
        serversTransport: "scrypted-insecure"
        servers:
          - url: "https://host.docker.internal:10443"
        passHostHeader: true
